# -*- coding: utf-8 -*-
"""CSB_DataExplore.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cZ_z5-l-yj6EW_q6aKDP2R3T1fUekD2H

# _Raw Data study and access with types and variations_

***Imports***
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plots

"""***Data access***"""

dtx=pd.read_csv("https://raw.githubusercontent.com/WolfDev8675/RepoSJX7/CaseStudy_backend/Data_static/HistoricalData_1628951636399.csv")
print(dtx.head(),"\n\n")
print(dtx.info())

"""***Plot for Close and High vs Date***"""

x=dtx.Date;
y=dtx['Close/Last'];
plots.plot(x,y)
plots.show()