# -*- coding: utf-8 -*-
"""API_yfinance.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mjAFWMiBEMeO_G9JV3s5X5wr0clhBgOd

Pre-run installation
"""

!pip install yfinance

"""***Imports***"""

import pandas as pd
import yfinance as yf

"""*Data access*"""

BrentCrude=yf.Ticker("BZ=F")
print(BrentCrude.info)
DTX_BrentC=BrentCrude.history(period="5y")
print(DTX_BrentC)